### ISSUE TITLE
Some questions on the Metro-NYC dataset

### ISSUE THREAD

**Issue by xiepeng21** [uctb/Urban-Dataset#26]
Thank you very much for providing the public transportation dataset along with the detailed introduction. Your work is invaluable. While exploring the data, I encountered a few questions and hope you can help clarify them:

**Flow Value of -1.0**: In the dataset, the flow value is recorded as -1.0. What does this signify? Is it indicative of missing data or something else?

**Station Count Discrepancy**: The passenger flow data indicates there are 424 stations, whereas the station information lists 426 stations. I noticed that two stations, Aqueduct Racetrack (A) and Aqueduct-N Conduit Av (A), share the same longitude and latitude (40.668236, -73.834061) but are listed as different stations. Could you confirm if there is corresponding station information for the 424 stations?

**Station Connection Diagram**: Is there a diagram or map showing the connection relationships between the stations?

Thank you for your attention to these questions.

**Comment by FangJiangyi** [comment]
Thanks for your attention.
1. -1.0 means that the value for this site at this time slot is missing.
2. We have already fixed this problem by uploading the correct file. 
3. Maybe you can find it on the [website](https://data.cityofnewyork.us/Transportation/Subway-Lines/3qz8-muuu).

**Comment by xiepeng21** [comment]
> Thanks for your attention.
> 
> 1. -1.0 means that the value for this site at this time slot is missing.
> 2. We have already fixed this problem by uploading the correct file.
> 3. Maybe you can find it on the [website](https://data.cityofnewyork.us/Transportation/Subway-Lines/3qz8-muuu).

Thank you again for your attention and reply.
